googleapis/python-storage

- google/cloud/storage/bucket.py
- google/cloud/storage/client.py
> fix(storage): fix documentation of max_result parameter in list_blob

- setup.py
Closes #14.
Closes #18.
This PR bumps google-auth version to benefit from its recent fixes, e.g. preventing unnecessary Timeout errors on long uploads.
Replaces [the same PR](https://github.com/googleapis/google-cloud-python/pull/10211) in the old repo.
> chore: bump google-auth dependency to v1.11.0+

- google/cloud/storage/_helpers.py
- google/cloud/storage/acl.py
- google/cloud/storage/batch.py
- google/cloud/storage/blob.py
- google/cloud/storage/bucket.py
- google/cloud/storage/client.py
- google/cloud/storage/constants.py
- google/cloud/storage/hmac_key.py
- google/cloud/storage/notification.py
- tests/unit/test__helpers.py
- tests/unit/test__http.py
- tests/unit/test_acl.py
- tests/unit/test_batch.py
- tests/unit/test_blob.py
- tests/unit/test_bucket.py
- tests/unit/test_client.py
- tests/unit/test_hmac_key.py
- tests/unit/test_notification.py
Closes #6.
Closes #13.
A replacement for [the same PR](https://github.com/googleapis/google-cloud-python/pull/10210) in the old repo.
- `ACL._ensure_loaded()` has a default timeout, but not all internal calls to it can be made that configurable, such as in `ACL.__iter__()`. I thus left that part to use a default timeout.
- `Blob.download_to_file()`,  `Blob.upload_from_file()`, and the methods that rely on these two do not expose timeouts, because the underlying `resumable-media` logic applies its own default timeout to `transport.request()`, which would override user timeouts.
Getting around that would first require adding configurable timeouts to the `resumable-media` dependency (there is a PR [#116](https://github.com/googleapis/google-resumable-media-python/pull/116) that adds these, …
> feat: add timeout parameter to public methods

- tests/system.py
> fix(tests): remove low version error assertion from iam conditions system tests

- tests/system.py
> fix(storage): fix system test and change scope for iam access token

- docs/snippets.py
- google/cloud/storage/bucket.py
- google/cloud/storage/client.py
- tests/unit/test_bucket.py
- tests/unit/test_client.py
> refactor(storage): deprecate Bucket.create() and requester_pays

- tests/system/test_system.py
Prep for factoring out e.g. signing tests into separate modules.
Port of https://github.com/googleapis/google-cloud-python/pull/9777
into new reposiory.
> tests: move system tests into a package

- google/cloud/storage/_signing.py
- tests/unit/test__signing.py
Fixes #12 
W/ exception of query string parameter quoting bits being addressed in PR #48.
> fix: make v4 signing formatting consistent w/ spec

- google/cloud/storage/blob.py
- tests/unit/test_blob.py
> fix(storage): fix blob metadata to None regression

- google/cloud/storage/blob.py
- google/cloud/storage/bucket.py
- tests/unit/test_blob.py
- tests/unit/test_bucket.py
> feat: generate signed URLs for blobs/buckets using virtual hostname

- .kokoro/continuous/storage_perf_bench.cfg
- tests/perf/benchwrapper.py
Perf tests are being moved to live service testing
> test: use a live endpoint for performance benchmarks

- google/cloud/storage/bucket.py
- google/cloud/storage/notification.py
- tests/system/test_system.py
- tests/unit/test_bucket.py
> feat(storage): add get notification method

- CHANGELOG.md
For context: https://github.com/googleapis/python-spanner/issues/28
> docs: fix URL for the old issue

- google/cloud/storage/_signing.py
- tests/unit/test__signing.py
> feat(storage): improve v4 signature query parameters encoding

- google/cloud/storage/blob.py
> docs(storage): add description and example to retrieve the hash of blob

- google/cloud/storage/_signing.py
- google/cloud/storage/blob.py
- google/cloud/storage/bucket.py
- tests/unit/test__signing.py
- tests/unit/test_blob.py
- tests/unit/test_bucket.py
- tests/unit/url_signer_v4_test_data.json
> feat(storage): Add cname support for V4 signature

- tests/unit/test__signing.py
- tests/unit/url_signer_v4_test_data.json
> feat(storage): add conformance tests for virtual hosted style signed URLs

- google/cloud/storage/_signing.py
- google/cloud/storage/blob.py
- google/cloud/storage/bucket.py
- tests/unit/test__signing.py
Just a docs update, so no body here.
> Fix typo in docs: paramters -> parameters

- google/cloud/storage/client.py
- tests/unit/test_client.py
Towards https://github.com/googleapis/python-storage/pull/64#issuecomment-607430718
Sometimes policy losses it's order while encoding into JSON. Adding `OrderedDict()` to fix this.
> fix(storage): use OrderedDict while encoding POST policy

- tests/unit/test__signing.py
- tests/unit/test_client.py
- tests/unit/url_signer_v4_test_data.json
Closes #92
Fields `signingV4Tests` and `postPolicyV4Tests` were added into `url_signer_v4_test_data.json` to separate signing test data from POST policies test data.
> test: update conformance tests to fit the new format

- docs/conf.py
> docs(storage): fix docs for new sphinx version

- google/cloud/storage/_signing.py
- tests/unit/test__signing.py
> fix(storage): remove expiration strict conversion

- google/cloud/storage/blob.py
- tests/system/test_system.py
- tests/unit/test_blob.py
These changes were originally made in another [PR](https://github.com/googleapis/python-storage/pull/98). Here is the version with changes requested by reviews.
Closes #16
> feat(storage): add arguments for *GenerationMatch uploading options

- tests/unit/test__signing.py
This code has been added a year ago, and is never used. `_CLIENT_TESTS` is always empty. Proposing to erase this code.
> test: delete client conformance tests dummy

- google/cloud/storage/_helpers.py
- tests/system/test_system.py
- tests/unit/test__helpers.py
> fix(storage): add projection parameter to blob.reload method

- google/cloud/storage/bucket.py
- google/cloud/storage/client.py
> fix(storage): add documentaion of list_blobs with user project

- google/cloud/storage/bucket.py
- tests/unit/test_bucket.py
> feat: add Bucket.reload() and Bucket.update() wrappers to restrict generation match args

- google/cloud/storage/blob.py
- tests/system/test_system.py
- tests/unit/test_blob.py
> fix(storage): fix upload object with bucket cmek enabled

- docs/snippets.py
> fix(storage): change the method names in snippets file

- google/cloud/storage/blob.py
- tests/system/test_system.py
- tests/unit/test__signing.py
- tests/unit/test_blob.py
Add `ifGenerationMatch` and `ifMetagenerationMatch` arguments into `Blob.compose()` method.
Towards #127
> feat: add *generation*match args into Blob.compose()

- google/cloud/storage/__init__.py
- google/cloud/storage/acl.py
- google/cloud/storage/bucket.py
- google/cloud/storage/client.py
> docs(storage): fix indent in code blocks

- tests/system/test_system.py
Default KMS key name is eventually consistent. Adding a retry for the test to avoid flaky failures.
Closes #190
> test: add retry for default kms system test

- google/cloud/storage/client.py
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-storage/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ x] Ensure the tests and linter pass
- [x ] Code coverage does not decrease (if any source code was changed)
- [ x] Appropriate docs were updated (if necessary)
Fixes #<issue_number_goes_here> 🦕
> docs: remove doubled word in docstring

- google/cloud/storage/blob.py
- tests/unit/test_blob.py
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #24  🦕
This PR autopopulates the following fields for non-chunked downloads based on the server header response:
```
blob.content_encoding
blob.content_type
blob.cache_control
blob.storage_class
blob.content_language
blob.md5_hash
blob.crc32c
```
> feat(blob.py): auto-populate standard headers for non-chunked downloads

- tests/system/test_system.py
See #226.  This PR doesn't *fix* the issue, because the KMS breakage exists:  it just skips the KMS systests under Python3, until we have dropped support for Python2.
> testing: fix / skip systests broken by dependency releases

- google/cloud/storage/client.py
- setup.py
- tests/system/test_system.py
packaging: pin 'google-cloud-core >= 1.4.0'
Closes #210
> feat: pass 'client_options' to base class ctor

- noxfile.py
- synth.py
- tests/system/test_system.py
> tests: pin google-cloud-kms to un-break systests

- google/cloud/storage/blob.py
- tests/system/test_system.py
- tests/unit/test_blob.py
> fix: extract hashes correctly during download

- tests/system/test_system.py
Fixes #239 
Tried to reproduce locally but no results so far, so adding a retry for the test to avoid flaky failures.
> test: add retry for bucket cmek enabled system test

- tests/system/test_system.py
Fixes #228  🦕
I think it's related to https://github.com/googleapis/python-storage/issues/244 issue so changed datetime.now() to datetime.utcnow()
> fix: change datetime.now to utcnow

- google/cloud/storage/blob.py
See: https://github.com/googleapis/python-storage/pull/199#discussion_r477519150
> fix: repair mal-formed docstring

- google/cloud/storage/_signing.py
- google/cloud/storage/blob.py
- google/cloud/storage/bucket.py
- google/cloud/storage/client.py
> docs: add docs signed_url expiration take default utc

- noxfile.py
- synth.py
Fixes #272 
For the passing current scenario restrict version in `nox.py` file and for the future added in synth.py file.
`google-cloud-pubsub==2.0.0` version has dropped the support of python2, so once storage will drop the support following changes needs to be done:
-  replace create_topic(self.topic_path) to create_topic(name=self.topic_path)
- replace get_iam_policy(self.topic_path) to get_iam_policy(request={"resource": self.topic_path})
- replace set_iam_policy(self.topic_path, policy) to set_iam_policy(request={"resource": self.topic_path, "policy": policy})
- replace delete_topic(self.topic_path) to delete_topic(request={"topic":self.topic_path})
> chore: restrict pubsub to  < 2.0

- google/cloud/storage/blob.py
> docs: fix docstring example for 'blob.generate_signed_url'

- tests/system/test_system.py
TestUnicode system tests are failing because a public repository of files was deleted. Rather than replace those public files, this PR self-uploads the files as per other tests.
While using a public bucket for this test had some advantages in test fidelity, the brittleness of relying on external static files is a significant problem and this is a compromise solution.
> fix: self-upload files for Unicode system test

- google/cloud/storage/_helpers.py
- google/cloud/storage/_http.py
- google/cloud/storage/blob.py
- google/cloud/storage/bucket.py
- google/cloud/storage/client.py
- google/cloud/storage/hmac_key.py
- google/cloud/storage/notification.py
- google/cloud/storage/retry.py
- tests/unit/test__helpers.py
- tests/unit/test__http.py
- tests/unit/test_blob.py
- tests/unit/test_bucket.py
- tests/unit/test_client.py
- tests/unit/test_hmac_key.py
- tests/unit/test_notification.py
- tests/unit/test_retry.py
> feat: retry API calls with exponential backoff

- google/cloud/storage/blob.py
- tests/unit/test_blob.py
> fix: preserve metadata value

- google/cloud/storage/blob.py
- google/cloud/storage/bucket.py
- google/cloud/storage/client.py
- tests/unit/test_blob.py
> fix: from_string method of blob and bucket class

- tests/unit/test_blob.py
> tests: cover 'Blob.download_as_string' when no hash matches

- tests/unit/test_blob.py
> tests: avoid depending on hash order

- google/cloud/storage/blob.py
- tests/unit/test_blob.py
This way '_PropertyMixin.patch' will send them to server.
Fixes #322 🦕
> fix: add change in 'Blob.custom_time' to changes

- google/cloud/storage/blob.py
- tests/unit/test_blob.py
Explicit 'encoding' overrides the fallback.
Use the 'charset' param of 'content_type', rather than 'content_encoding',
which isn't going to be a Unicode -> bytes encoding.
Closes #319.
> fix: fall back to 'charset' of 'content_type' in 'download_as_text' 

- google/cloud/storage/blob.py
- tests/unit/test_blob.py
> fix: avoid triggering global logging config

- google/cloud/storage/_helpers.py
- google/cloud/storage/acl.py
- google/cloud/storage/blob.py
- google/cloud/storage/bucket.py
- google/cloud/storage/client.py
- google/cloud/storage/hmac_key.py
- google/cloud/storage/notification.py
- tests/unit/test_acl.py
- tests/unit/test_blob.py
- tests/unit/test_bucket.py
- tests/unit/test_hmac_key.py
- tests/unit/test_notification.py
> feat: make retry parameter public and added in other methods

- google/cloud/storage/retry.py
- tests/unit/test_retry.py
A customer reported difficulty with if_metageneration_match conditional retries. It turned out to be confusion in the retry code over snake case vs. camel case query params; this will resolve that issue.
> fix: fix conditional retry handling of camelCase query params

- setup.py
Bump the google-resumable-media-python library requirement to pull in changes that support retries on ConnectionError for media operations.
> feat: support ConnectionError retries for media operations

- docs/snippets.py
- google/cloud/storage/blob.py
- tests/system/test_system.py
- tests/unit/test_blob.py
> refactor: replace deprecated method calls for new client methods

- google/cloud/storage/blob.py
- google/cloud/storage/bucket.py
- google/cloud/storage/client.py
- tests/unit/test_blob.py
- tests/unit/test_bucket.py
- tests/unit/test_client.py
Fixes: #357 
The bug exposed a hole in our testing of the new retry defaults, so this PR also adds some simple tests to verify defaults are correct. It doesn't try to comprehensively validate all defaults throughout the library, but the existence of this bug suggests we might want to audit those to make sure.
> fix: Amend default retry behavior for bucket operations on client

- google/cloud/storage/bucket.py
- tests/unit/test_bucket.py
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #364 🦕
> fix: address incorrect usage of request preconditions

- google/cloud/storage/blob.py
- tests/system/test_system.py
The custom_time property was incorrectly not included as a field
that could be set on object upload.
Fixes #372
> fix: set custom_time on uploads

- samples/README.md
- samples/snippets/storage_create_bucket_location.py
There was a space that shouldn't have been there for linking the fileio samples and looks like the turbo replication samples didn't get properly linked in the readme, so this fixes both of those.
> cleanup: add turbo rep samples and fix spacing on fileio samples

- samples/snippets/snippets_test.py
- samples/snippets/storage_transfer_manager_download_all_blobs.py
- samples/snippets/storage_transfer_manager_download_chunks_concurrently.py
- samples/snippets/storage_transfer_manager_upload_directory.py
- samples/snippets/storage_transfer_manager_upload_many_blobs.py
- Remove deprecated argument "threads" in transfer_manager samples
- Use "processes" in transfer_manager samples and set default number to be 8
- Call "max_workers" when calling transfer_manager functions
- Refactor transfer_manager sample tests accordingly
Fixes #1028  🦕
> docs: remove threads in transfer manager samples

- samples/snippets/storage_get_rpo.py
There was an extra line here that doesn't make sense. Fixing based on external user feedback.
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes b/318488404 🦕
> chore: fix get RPO sample

- samples/snippets/noxfile_config.py
- samples/snippets/snippets_test.py
- samples/snippets/storage_create_bucket_hierarchical_namespace.py
> samples: create bucket with HNS enabled

- samples/snippets/storage_list_files_with_prefix.py
If a user wants to just list prefixes without listing the blob names they can do so by following the updated documentation.
Fixes internal b/434195405
> chore: improve docs for list_files_with_prefix
