google/cloud/storage/iam.py
Post-repo-split port of
https://github.com/googleapis/google-cloud-python/pull/10193
=> fix: use correct IAM object admin role

google/cloud/storage/notification.py
=> fix(storage): remove docstring of retrun in reload method

google/cloud/storage/_helpers.py, google/cloud/storage/_signing.py, google/cloud/storage/acl.py, google/cloud/storage/batch.py, google/cloud/storage/blob.py, google/cloud/storage/bucket.py, google/cloud/storage/client.py, google/cloud/storage/hmac_key.py, google/cloud/storage/notification.py
=> refactor(storage): consistent use of optional keyword

tests/unit/url_signer_v4_test_data.json
Update conformance tests data for V4 POST policies to follow the [PR](https://github.com/googleapis/conformance-tests/pull/29)
=> test: update conformance tests for V4 POST policies

google/cloud/storage/_signing.py
Fixes #139 
This PR fixes a lint error that recently started occurring on master out of the blue.
Run the lint check on master:
$ nox -f noxfile.py -s lint
=> chore(storage): fix lint error in _signing.py module

google/cloud/storage/bucket.py
=> docs(storage): fix documentation

google/cloud/storage/_helpers.py
=> fix(storage): remove unused variables

google/cloud/storage/blob.py
=> docs(storage): add documentation about upload and download

google/cloud/storage/blob.py
=> docs(storage): add document about default chunk size

synth.py
Should resolve CI issues in #164
=> fix: add multiprocessing.rst to synthool excludes

google/cloud/storage/_signing.py, tests/unit/test__signing.py
=> feat(storage): migrate to Service Account Credentials API

google/cloud/storage/bucket.py
`patch()` doesn't return anything, so this `return` statement looks little bit confusing
=> refactor(storage): erase excess return

tests/unit/test_client.py
=> tests: unit tests pass w/o environ vars

setup.py
=> chore(packaging): prep for grmp-1.0.0 release

tests/unit/test_blob.py
=> tests: add unit test to fix coverage

tests/system/test_system.py
=> tests: fix the system tests

setup.py
=> chore: bump g-c-c to 1.4.1

setup.py
=> fix: add requests as a dependency

tests/system/test_system.py
=> tests: bump max retries for 429/503

tests/system/test_system.py
=> tests: normailze systest data paths for Windows

.pre-commit-config.yaml, CONTRIBUTING.rst
Document how to enable it in 'CONTRIBUTING.rst'.
=> chore: add config for 'pre-commit' support

samples/snippets/snippets_test.py, samples/snippets/storage_set_client_endpoint.py
Adds sample for changing endpoint on client.
One note: I accidentally merged an earlier version of this sample into my last README fix, which is why this includes a deletion as well. Oops.
=> samples: add endpoint sample

samples/snippets/storage_get_metadata.py
Fixes internal issue 153524869
=> samples: Adding MediaLink to Get Metadata sample

samples/snippets/notification_polling.py
=> samples(docs): remove beta tag in gcloud command

samples/snippets/snippets_test.py, samples/snippets/storage_create_bucket_dual_region.py
=> samples: update dual-region bucket creation sample output

samples/README.md, samples/snippets/requester_pays_test.py, samples/snippets/snippets_test.py
- update snippets_test to gracefully handle empty env vars
- clarify testing section in samples readme
- add backoff retries to requester pays samples tests
=> chore: update samples testing and readme

samples/snippets/snippets_test.py, samples/snippets/storage_create_bucket_object_retention.py, samples/snippets/storage_get_bucket_metadata.py, samples/snippets/storage_get_metadata.py, samples/snippets/storage_set_object_retention_policy.py
=> samples: add samples for object retention
